# Generated by Django 2.2.7 on 2019-11-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
