# Generated by Django 2.2.8 on 2019-12-13 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('prebooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.Prebooking')),
            ],
        ),
    ]
