# Generated by Django 2.2.8 on 2019-12-13 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.CharField(default=datetime.datetime(2019, 12, 13, 15, 33, 41, 878032, tzinfo=utc), max_length=5000),
            preserve_default=False,
        ),
    ]
